### ISSUE TITLE
kick.com still producing 404 bad request error with hz+ active, after version update meant to fix this issue

### ISSUE THREAD

**Issue by eitaniel** [extesy/hoverzoom#1174]
**ATTENTION!** If you don't follow this template then your issue will be immediately closed.

## Description of the problem

greetings

i'm writing to confirm that the fixes you stated you'd perform for hz+ on kick.com seem to not have been implemented. I am still getting 404 bad request error page upon activating hz+ and attempting to surf kick.com. it's almost instant fail. 

did you implement the fixes you suggested would be done according to this issues thread? I've had the addon deactivated as recommended since early June, with the hope of it being fixed as stated in this thread with the next version update (1.0.207), so it's confusing why this seems not to be the case. 

I raised this issue two months ago in this post: https://github.com/extesy/hoverzoom/issues/1156

## Url of the page where the problem occurs (not the image url)

kick.com

## Steps to reproduce the problem (include image url here)
1. activate hover zoom plus, with no site exceptions (ie. normal function to be active on all sites online)
2. visit kick.com, and start surfing normally, therein. 
3. site will produce 404 bad request and eventually not load the site on refresh

## OS version, extension version

windows 10 pro
hz+ v. 1.0.207

![kickstreaming brave browser 400 bad request](https://github.com/extesy/hoverzoom/assets/24715620/1c717ce6-e37b-4fef-bb0d-e61c04516c82)

**Comment by GrosPoulet** [comment]
@eitaniel i did not manage to reproduce the issue. Please remove & add back HZ+ then try again.
BTW, i fixed a bug with clips (#1178), not related with the issue you reported.

**Comment by eitaniel** [comment]
> @eitaniel i did not manage to reproduce the issue. Please remove & add back HZ+ then try again. BTW, i fixed a bug with clips (#1178), not related with the issue you reported.

greetings guys

i just tried using hz+ on opera browser now, freshly installed browser that i'd never used, with freshly installed hz+ extension/addon from chrome webstore. 

went to kick.com with hz+ active (without placing kick.com as an exception site, ie fully operational on kick.com). and the moment i clicked the kick icon on top left of screen, to essentially refresh the page, instantly opera gave me a 'bad request' blank page. 

the issue still exists. I personally never mentioned something about clips, my main issue was that the website itself seems to break completely, with hz+ active/on. I thought i'd made this clear in my original issue report, and that the issue was understood and had been fixed as stated for this current (new) version. 

I'm not sure why the issue isn't 'reproducible'. it's a fresh install of hz+ off of chrome webstore.

**Comment by GrosPoulet** [comment]
@eitaniel i did exactly the same: fresh install on Opera: it works perfectly.
I can also read videos from Google search page (search for: **site:kick.com/video**)
Opera: 100.0.4815.84
Win 10 Pro 22H2 build: 19045.3208

**Comment by eitaniel** [comment]
@GrosPoulet  thanks for feedback

were you able to look at the reddit link i posted at the end of my last message, showing that several people, even until recently, still have this problem? i think the issue probably manifests itself when people log into their kick.com accounts. i tried using a freshly 'reinstalled' hz+ on brave browser a few minutes ago, and found, before logging into my kick.com account that things SEEMED fine. for a minute or two. after logging in, with my credentials, i found that within 1 minute, the 404 bad request error popped up and the site was thereafter totally inaccessible. 

https://www.reddit.com/r/brave_browser/comments/13opjk9/400_bad_request_kickcom_kickstreaming_error_fix/?sort=new

BRAVE: [Version 1.56.14 Chromium: 115.0.5790.114 (Official Build) (64-bit)](https://brave.com/latest/)
OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045

**Comment by JoshLambda** [comment]
Same problem.

OS: Windows 10
Browser: Google Chrome Version 115.0.5790.110 (Official Build) (64-bit)
HZ+: Version 1.0.207

- With HZ+ installed it's impossible to access kick.com, only getting errors 400/404.
- It works again when adding kick.com to exclude list in HZ+ settings AND clearing cookies.
- When removing kick.com from exclude list it keeps working for ~10 minutes then the errors appear again.

I can repeat the issue with 100% accuracy using the process above.

**Comment by eitaniel** [comment]
> Same problem.
> 
> OS: Windows 10 Browser: Google Chrome Version 115.0.5790.110 (Official Build) (64-bit) HZ+: Version 1.0.207
> 
> * With HZ+ installed it's impossible to access kick.com, only getting errors 400/404.
> * It works again when adding kick.com to exclude list in HZ+ settings AND clearing cookies.
> * When removing kick.com from exclude list it keeps working for ~10 minutes then the errors appear again.
> 
> I can repeat the issue with 100% accuracy using the process above.

thank you @JoshLambda for confirming that i'm not losing my mind! lol

**Comment by extesy** [comment]
@GrosPoulet Since clearing cookies fixes the problem, I suspect it might be related to the "header rewrite" feature which is caching some headers that break Kick and it becomes impossible to unbreak it without removing those cached values.

**Comment by eitaniel** [comment]
interesting. 

what i've found is happening now is that after i've checked the box of the feature @extesy has mentioned above ("Allow rewrite of headers for HTTP(S) request or response"), kick.com doesn't break in the same manner it has previously. 

what happens now is that kick.com logs me out after a few minutes of browsing, but i dont get the 404/400 bad request error anymore, even after several clicks over a period of time, of the "kick beta" header. 

prior to this, i had never ticked the box for the headers feature. ever. it was 'inactive' as a feature on my personal use of hz+. after extesy mentioned the feature, i tried activating it and seeing what results i'd get, which are described above.

**Comment by GrosPoulet** [comment]
@eitaniel 
I still did not managed to reproduce this issue.
**=> could you please try to find out which cookie triggers the logout ?**
You might let DevTools window opened with Kick.com cookies displayed as you surf the site.
As soon as you get logged out, check which cookie was added/modified.
Plug-in for kick.com might be able to patch it on the fly to prevent logout.

**Comment by extesy** [comment]
I think cookies is a red herring here. When you clear cookies for a site, you _also_ clear local storage:
![image](https://github.com/extesy/hoverzoom/assets/65872/62454a35-98bd-4914-9680-d9e065b69d7d)
@GrosPoulet The `storeHeaderSettings` is suspect, not the cookies. But I could be wrong, of course.

**Comment by eitaniel** [comment]
@extesy it's not that the site 'works perfectly', the site logs me out with "headers rewrite" enabled. 

hence, i can't use the site with my personal account, ie can't use my dashboard, can't see my 'followed' creators to the left panel of kick's site, as well as any other personalized experience offered by kick with a personal account. 

the site 'functions' decently ("normally") without generating the 400/404 bad request error, which basically makes the site inaccessible once generated. 

i was testing how the site would respond to hz+ if "headers rewrite" was enabled, and thereafter, disabled. 

"headers rewrite" enabled = site doesn't completely break, no 400/404 bad request error, general surfing, NO PERSONAL ACCOUNT ACCESSIBILITY (logs me off the site after few seconds/mins)

"headers rewrite" disabled = after few seconds/mins, kick.com breaks completely, inaccessible. 404/400 bad request site error generated. deleting cookies and rebooting site, temporarily restores kick.com, thereafter, with few mins browsing, site breaks again.

**Comment by Jd-19** [comment]
Same issue for me for several weeks now. Same "400 bad request" error

**Comment by eitaniel** [comment]
is there any other way that we can help the devs clearly identify what could be happening here for several people, between this github thread, and my post on reddit with similar comments?

**Comment by eitaniel** [comment]
btw, just wanted to say that this issue is now resolved. i didn't notice when the issue resolved exactly, but my feeling is that it coincided with v1 of KICK.com. 

i now use kick without any issue while this extension is enabled in my browser, and all the app's features work smoothly on kick.com, none of the issues i reported materialize anymore. 

thank you devs.
